insert into product (brand, category, price) VALUES ('A', '상의', 11200);
insert into product (brand, category, price) VALUES ('B', '상의', 10500);
insert into product (brand, category, price) VALUES ('C', '상의', 10000);
insert into product (brand, category, price) VALUES ('D', '상의', 10100);
insert into product (brand, category, price) VALUES ('E', '상의', 10700);
insert into product (brand, category, price) VALUES ('F', '상의', 11200);
insert into product (brand, category, price) VALUES ('G', '상의', 10500);
insert into product (brand, category, price) VALUES ('H', '상의', 10800);
insert into product (brand, category, price) VALUES ('I', '상의', 11400);

insert into product (brand, category, price) VALUES ('A', '아우터', 5500);
insert into product (brand, category, price) VALUES ('B', '아우터', 5900);
insert into product (brand, category, price) VALUES ('C', '아우터', 6200);
insert into product (brand, category, price) VALUES ('D', '아우터', 5100);
insert into product (brand, category, price) VALUES ('E', '아우터', 5000);
insert into product (brand, category, price) VALUES ('F', '아우터', 7200);
insert into product (brand, category, price) VALUES ('G', '아우터', 5800);
insert into product (brand, category, price) VALUES ('H', '아우터', 6300);
insert into product (brand, category, price) VALUES ('I', '아우터', 6700);

insert into product (brand, category, price) VALUES ('A', '바지', 4200);
insert into product (brand, category, price) VALUES ('B', '바지', 3800);
insert into product (brand, category, price) VALUES ('C', '바지', 3300);
insert into product (brand, category, price) VALUES ('D', '바지', 3000);
insert into product (brand, category, price) VALUES ('E', '바지', 3800);
insert into product (brand, category, price) VALUES ('F', '바지', 4000);
insert into product (brand, category, price) VALUES ('G', '바지', 3900);
insert into product (brand, category, price) VALUES ('H', '바지', 3100);
insert into product (brand, category, price) VALUES ('I', '바지', 3200);

insert into product (brand, category, price) VALUES ('A', '스니커즈', 9000);
insert into product (brand, category, price) VALUES ('B', '스니커즈', 9100);
insert into product (brand, category, price) VALUES ('C', '스니커즈', 9200);
insert into product (brand, category, price) VALUES ('D', '스니커즈', 9500);
insert into product (brand, category, price) VALUES ('E', '스니커즈', 9900);
insert into product (brand, category, price) VALUES ('F', '스니커즈', 9300);
insert into product (brand, category, price) VALUES ('G', '스니커즈', 9000);
insert into product (brand, category, price) VALUES ('H', '스니커즈', 9700);
insert into product (brand, category, price) VALUES ('I', '스니커즈', 9500);

insert into product (brand, category, price) VALUES ('A', '가방', 2000);
insert into product (brand, category, price) VALUES ('B', '가방', 2100);
insert into product (brand, category, price) VALUES ('C', '가방', 2200);
insert into product (brand, category, price) VALUES ('D', '가방', 2500);
insert into product (brand, category, price) VALUES ('E', '가방', 2300);
insert into product (brand, category, price) VALUES ('F', '가방', 2100);
insert into product (brand, category, price) VALUES ('G', '가방', 2200);
insert into product (brand, category, price) VALUES ('H', '가방', 2100);
insert into product (brand, category, price) VALUES ('I', '가방', 2400);

insert into product (brand, category, price) VALUES ('A', '모자', 1700);
insert into product (brand, category, price) VALUES ('B', '모자', 2000);
insert into product (brand, category, price) VALUES ('C', '모자', 1900);
insert into product (brand, category, price) VALUES ('D', '모자', 1500);
insert into product (brand, category, price) VALUES ('E', '모자', 1800);
insert into product (brand, category, price) VALUES ('F', '모자', 1600);
insert into product (brand, category, price) VALUES ('G', '모자', 1700);
insert into product (brand, category, price) VALUES ('H', '모자', 1600);
insert into product (brand, category, price) VALUES ('I', '모자', 1700);

insert into product (brand, category, price) VALUES ('A', '양말', 1800);
insert into product (brand, category, price) VALUES ('B', '양말', 2000);
insert into product (brand, category, price) VALUES ('C', '양말', 2200);
insert into product (brand, category, price) VALUES ('D', '양말', 2400);
insert into product (brand, category, price) VALUES ('E', '양말', 2100);
insert into product (brand, category, price) VALUES ('F', '양말', 2300);
insert into product (brand, category, price) VALUES ('G', '양말', 2100);
insert into product (brand, category, price) VALUES ('H', '양말', 2000);
insert into product (brand, category, price) VALUES ('I', '양말', 1700);

insert into product (brand, category, price) VALUES ('A', '액세서리', 2300);
insert into product (brand, category, price) VALUES ('B', '액세서리', 2200);
insert into product (brand, category, price) VALUES ('C', '액세서리', 2100);
insert into product (brand, category, price) VALUES ('D', '액세서리', 2000);
insert into product (brand, category, price) VALUES ('E', '액세서리', 2100);
insert into product (brand, category, price) VALUES ('F', '액세서리', 1900);
insert into product (brand, category, price) VALUES ('G', '액세서리', 2000);
insert into product (brand, category, price) VALUES ('H', '액세서리', 2000);
insert into product (brand, category, price) VALUES ('I', '액세서리', 2400);
